import type { Product } from './types'

// Fallback catalogue used when the external API is unreachable, so the gallery
// always renders. Once NEXT_PUBLIC_API_URL is live, real data takes precedence.
export const DEMO_PRODUCTS: Product[] = [
  {
    id: '1111-01',
    title: 'Threshold',
    series: 'Apparitions',
    year: 2025,
    price: 1500,
    image: '/artworks/art-1.png',
    medium: 'Archival pigment print with AR layer',
    dimensions: '90 × 120 cm',
    editionSize: 100,
    editionRemaining: 42,
    availability: 'low',
    description:
      'A figure caught between states, rendered in champagne light. When viewed through the companion lens, the filaments breathe and unravel across the room — a private aurora for the collector.',
    arDurationSeconds: 38,
  },
  {
    id: '1111-02',
    title: 'Dissolve',
    series: 'Apparitions',
    year: 2025,
    price: 1200,
    image: '/artworks/art-2.png',
    medium: 'Archival pigment print with AR layer',
    dimensions: '80 × 100 cm',
    editionSize: 100,
    editionRemaining: 71,
    availability: 'available',
    description:
      'A portrait surrendering to gold particulate. The augmented layer scatters the sitter into a slow constellation that reassembles as you approach.',
    arDurationSeconds: 42,
  },
  {
    id: '1111-03',
    title: 'Portal I',
    series: 'Horizons',
    year: 2024,
    price: 950,
    image: '/artworks/art-3.png',
    medium: 'Archival pigment print with AR layer',
    dimensions: '100 × 100 cm',
    editionSize: 150,
    editionRemaining: 108,
    availability: 'available',
    description:
      'A single geometric portal on a darkened horizon. In augmented reality the aperture opens, casting a shifting field of light onto the wall beyond the frame.',
    arDurationSeconds: 30,
  },
  {
    id: '1111-04',
    title: 'Gilded Bloom',
    series: 'Still Life',
    year: 2024,
    price: 800,
    image: '/artworks/art-4.png',
    medium: 'Archival pigment print with AR layer',
    dimensions: '70 × 90 cm',
    editionSize: 200,
    editionRemaining: 3,
    availability: 'low',
    description:
      'A baroque botanical cast in liquid gold. The animation lets the bloom open and close with the rhythm of a held breath.',
    arDurationSeconds: 26,
  },
  {
    id: '1111-05',
    title: 'Nebula 1111',
    series: 'Horizons',
    year: 2025,
    price: 1350,
    image: '/artworks/art-5.png',
    medium: 'Archival pigment print with AR layer',
    dimensions: '110 × 140 cm',
    editionSize: 75,
    editionRemaining: 0,
    availability: 'sold',
    description:
      'The flagship of the 1111 series. An indigo nebula threaded with gold, its augmented layer drifting in perpetual, non-repeating motion.',
    arDurationSeconds: 55,
  },
  {
    id: '1111-06',
    title: 'Gesture (Gold)',
    series: 'Marks',
    year: 2023,
    price: 400,
    image: '/artworks/art-6.png',
    medium: 'Archival pigment print with AR layer',
    dimensions: '60 × 80 cm',
    editionSize: 300,
    editionRemaining: 194,
    availability: 'available',
    description:
      'A single calligraphic stroke in gold ink. The entry point to the collection — its AR layer redraws the gesture, stroke by stroke, on command.',
    arDurationSeconds: 18,
  },
  {
    id: '1111-07',
    title: 'Horizon Line',
    series: 'Horizon',
    year: 2025,
    price: 1250,
    image: 'https://cdn.guardian.ng/wp-content/uploads/2021/08/IMG_2100.jpeg',
    medium: 'Archival pigment print with AR layer',
    dimensions: '100 × 130 cm',
    editionSize: 111,
    editionRemaining: 63,
    availability: 'available',
    description:
      "The collection's founding view of the horizon — a still line the augmented layer slowly sets in motion, dissolving the boundary between the framed and the room around it.",
    arDurationSeconds: 40,
  },
  {
    id: '1111-08',
    title: 'Ember Fields',
    series: 'Chromatic Studies',
    year: 2024,
    price: 890,
    image:
      'https://images.unsplash.com/photo-1623855584723-53764e27c7c2?fm=jpg&q=80&w=1600&auto=format&fit=crop',
    medium: 'Archival pigment print with AR layer',
    dimensions: '80 × 100 cm',
    editionSize: 250,
    editionRemaining: 187,
    availability: 'available',
    description:
      'Loose gold particulate suspended in near-darkness. The AR layer sets each grain drifting, slow as embers cooling in still air.',
    arDurationSeconds: 24,
  },
  {
    id: '1111-09',
    title: 'Verdant Static',
    series: 'Chromatic Studies',
    year: 2024,
    price: 1150,
    image:
      'https://images.unsplash.com/photo-1630222927215-a6a21f236d72?fm=jpg&q=80&w=1600&auto=format&fit=crop',
    medium: 'Archival pigment print with AR layer',
    dimensions: '90 × 110 cm',
    editionSize: 200,
    editionRemaining: 140,
    availability: 'available',
    description:
      'Chlorophyll green pressed against burnt orange. Its augmented layer reads like interference on an old signal — a field that never quite settles.',
    arDurationSeconds: 33,
  },
  {
    id: '1111-10',
    title: 'Spectral Drift',
    series: 'Chromatic Studies',
    year: 2025,
    price: 1340,
    image:
      'https://images.unsplash.com/photo-1630222927205-d5ffdf3aac59?fm=jpg&q=80&w=1600&auto=format&fit=crop',
    medium: 'Archival pigment print with AR layer',
    dimensions: '100 × 120 cm',
    editionSize: 175,
    editionRemaining: 22,
    availability: 'low',
    description:
      'Three colors refusing to resolve into one another. The AR layer keeps them permanently mid-negotiation, never quite blending, never quite apart.',
    arDurationSeconds: 36,
  },
  {
    id: '1111-11',
    title: 'Deep Current',
    series: 'Chromatic Studies',
    year: 2023,
    price: 760,
    image:
      'https://images.unsplash.com/photo-1599422314077-f4dfdaa4cd09?fm=jpg&q=80&w=1600&auto=format&fit=crop',
    medium: 'Archival pigment print with AR layer',
    dimensions: '70 × 90 cm',
    editionSize: 300,
    editionRemaining: 264,
    availability: 'available',
    description:
      'Indigo folding over itself like water at depth. The most affordable entry point into the Chromatic Studies, its AR layer stirs slowly, tide-like, on a loop.',
    arDurationSeconds: 28,
  },
  {
    id: '1111-12',
    title: 'Untamed (Study I)',
    series: 'Wild Portraits',
    year: 2025,
    price: 980,
    image:
      'https://images.unsplash.com/photo-1756835506989-9130ff1c4d62?fm=jpg&q=80&w=1600&auto=format&fit=crop',
    medium: 'Archival pigment print with AR layer',
    dimensions: '90 × 120 cm',
    editionSize: 175,
    editionRemaining: 121,
    availability: 'available',
    description:
      'A black horse held mid-stillness against a stable\'s dark. The AR layer sets its mane and breath in motion — a private paddock summoned onto any wall.',
    arDurationSeconds: 32,
  },
  {
    id: '1111-13',
    title: 'Veiled',
    series: 'Wild Portraits',
    year: 2025,
    price: 1420,
    image:
      'https://images.unsplash.com/photo-1705941469812-37d919182bb5?fm=jpg&q=80&w=1600&auto=format&fit=crop',
    medium: 'Archival pigment print with AR layer',
    dimensions: '80 × 100 cm',
    editionSize: 120,
    editionRemaining: 58,
    availability: 'available',
    description:
      'A face composed behind sheer fabric, eyes closed in quiet withholding. The augmented layer lifts and settles the veil on a slow, private rhythm.',
    arDurationSeconds: 30,
  },
]

export const FRAMING_OPTIONS = [
  { id: 'natural-oak', label: 'Natural Oak', priceModifier: 0 },
  { id: 'matte-black', label: 'Matte Black', priceModifier: 120 },
  { id: 'gilded', label: 'Hand-Gilded', priceModifier: 340 },
  { id: 'unframed', label: 'Unframed (rolled)', priceModifier: -180 },
]
